1.创建一个值为从10到49的向量`[10,11,12...49]`

In [10]:
import numpy as np
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2.创建一个3x3矩阵，其值范围为0到8

In [11]:
b=np.arange(0,9).reshape(3,3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3.反转一个向量（第一个元素变为最后一个）

In [12]:
a=a[::-1]
print(a)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


4.使用随机值创建一个10x10数组，并找出其最小值，最大值和平均值

In [14]:
c=np.random.rand(10,10)
print(c)
print(np.min(c))
print(np.max(c))
print(np.average(c))

[[0.74228097 0.88585283 0.73217974 0.56784829 0.67310666 0.0916314
  0.31612471 0.19555994 0.94764105 0.56518298]
 [0.30740484 0.01608964 0.05933921 0.22274546 0.73066698 0.5004966
  0.08701353 0.47972611 0.9190864  0.30039608]
 [0.35563645 0.95236701 0.50692142 0.16740887 0.18868693 0.07283541
  0.74164306 0.62738174 0.71276486 0.60365573]
 [0.92086564 0.81683257 0.47738152 0.44326829 0.52073607 0.7424713
  0.94062843 0.66969371 0.0885925  0.41263212]
 [0.59735198 0.07385222 0.22186784 0.71402499 0.8407451  0.12452466
  0.13607378 0.40170818 0.3543158  0.15800528]
 [0.58665153 0.3291345  0.0100665  0.92426954 0.34938253 0.45437845
  0.03377494 0.42995845 0.35886721 0.26154874]
 [0.20202199 0.74464984 0.62742924 0.96362817 0.38713476 0.21824266
  0.38638215 0.97170794 0.66152211 0.58209252]
 [0.87004998 0.76045231 0.02369986 0.73409236 0.95963198 0.11649363
  0.7459816  0.07740136 0.76251162 0.79699703]
 [0.84693641 0.05671961 0.34038738 0.778138   0.95590537 0.22836317
  0.40524415 0.

创建一个5x5矩阵, 其对角线下方的数值正好是1,2,3,4
```python
[[0, 0, 0, 0, 0],
[1, 0, 0, 0, 0],
[0, 2, 0, 0, 0],
[0, 0, 3, 0, 0],
[0, 0, 0, 4, 0]]
```

5.5x3矩阵乘以3x2矩阵(矩阵乘法)

In [16]:
x1=np.arange(1,16).reshape(5,3)
x2=np.arange(1,7).reshape(3,2)
print(np.dot(x1,x2))

[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


6.使用numpy创建一个10x10形状，元素在`[0,1]`均匀分布的矩阵，并且将其中小于0.5的元素置为0，其他元素不变
例如：
```python
[[0.1, 0.6],      [[0.0, 0.6],
[0.8, 1.34]]  ->  [0.8, 0.0]]
```

In [19]:
x=np.linspace(0,1,100).reshape(10,10)
x[x<0.5]=0
print(x)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.        ]
 [0.50505051 0.51515152 0.52525253 0.53535354 0.54545455 0.55555556
  0.56565657 0.57575758 0.58585859 0.5959596 ]
 [0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
  0.66666667 0.67676768 0.68686869 0.6969697 ]
 [0.70707071 0.71717172 0.72727273 0.73737374 0.74747475 0.75757576
  0.76767677 0.77777778 0.78787879 0.7979798 ]
 [0.80808081 0.81818182 0.82828283 0.83838384 0.84848485 0.85858586
  0.86868687 0.87878788 0.88888889 0.8989899 ]
 [0.9

7.创建两个长度为100的向量，求向量的点积和夹角(提示:使用np.linalg的函数)

In [24]:
v1=np.array([1,2])
v2=np.array([1,3])
print(np.vdot(v1,v2))
print(np.linalg.norm(v1))
print(np.linalg.norm(v2))
print(np.arccos(np.vdot(v1,v2)/(np.linalg.norm(v1)*np.linalg.norm(v2))))

7
2.23606797749979
3.1622776601683795
0.14189705460416518


8. 给定一个随机整数矩阵input，和一个mask整数矩阵，请你找出input和mask值相同的坐标，并且在input中把这些位置置为0

In [29]:
import numpy as np
input = np.random.randint(1, 1000, size=(3, 1000, 1000))
mask = np.random.randint(1,1000, size=(3, 1000,1000))

# complete your code
# maybe there's a better way.
for i in range(3):
    for j in range(1000):
        for k in range(1000):
            if input[i][j][k]==mask[i][j][k]:
                input[i][j][k]=0
print(input)

[[[868 570 798 ... 203 735 100]
  [341 567 795 ... 426 379 108]
  [253 774 180 ... 240 401  94]
  ...
  [240 647 839 ... 272 896 228]
  [962 386 740 ... 690 674 596]
  [216  17 260 ... 746 296 267]]

 [[571 691  43 ... 944 464 173]
  [502 292 994 ... 559 185 632]
  [109 302 652 ... 582   8 197]
  ...
  [835 742 579 ... 860 723 706]
  [132  74   1 ... 641 710 263]
  [380 604 517 ... 573 953 175]]

 [[996 818 296 ... 689 795 949]
  [318 470 618 ...  90 439  29]
  [553  81 557 ... 198 109 779]
  ...
  [397 473 858 ... 914 999 193]
  [807 772 269 ... 619 380 480]
  [ 88 968  38 ... 558 390 565]]]
[[[868 570 798 ... 203 735 100]
  [341 567 795 ... 426 379 108]
  [253 774 180 ... 240 401  94]
  ...
  [240 647 839 ... 272 896 228]
  [962 386 740 ... 690 674 596]
  [216  17 260 ... 746 296 267]]

 [[571 691  43 ... 944 464 173]
  [502 292 994 ... 559 185 632]
  [109 302 652 ... 582   8 197]
  ...
  [835 742 579 ... 860 723 706]
  [132  74   1 ... 641 710 263]
  [380 604 517 ... 573 953 175]]

